### ISSUE TITLE
Could u provide FPS?

### ISSUE THREAD

**Issue by TsingWei** [IDEA-Research/Lite-DETR#1]
Just wonder why there is no FPS compared with other methods in the paper.

**Comment by FengLi-ust** [comment]
We did not optimize the inference speed, especially the KDA attention that needs to be implemented with CUDA implementation (currently in PyTorch) for fast inference speed.

**Comment by TsingWei** [comment]
Is KDA a plug-and-play alternative to Deformable Attention?

**Comment by FengLi-ust** [comment]
Yes. You can safely use the original deformable attention, and the performance will not be influenced by a large margin.

**Comment by TsingWei** [comment]
I noticed that the attn weight is predicted by MLP in original deformable attention, however, in Fig.3 the attn weight is produced by the dot-product operation.  Is this the ![](https://pdf.cdn.readpaper.com/parsed/fetch_target/bc5b7e5f13805240b66ee7cd9a88e6ac_4_Figure_3_-1485407967.png)
