### ISSUE TITLE
Looking forward to release soon! 

### ISSUE THREAD

**Issue by Wilbur529** [IDEA-Research/Lite-DETR#3]
Fantastic work! Looking forward to release soon!

**Comment by amazing-cc** [comment]
Does the team have a plan for when the code will be released?

**Comment by FengLi-ust** [comment]
Yes. The code is under preparing and will be released soon. Stay tuned!

**Comment by Markson-Young** [comment]
Hope you can publish a todo list as soon as possible. It's a attractive job.
Looking forward to release soon!

**Comment by eorroot** [comment]
I was impressed with your work on "Lite DETR : An Interleaved Multi-Scale Encoder for Efficient DETR
" and would like to express my appreciation for your contributions.
 I'm wondering if you have any plans to release the source code of this project on GitHub or any other platform. I believe many people in the community would benefit from being able to learn from and build upon your work.

**Comment by FengLi-ust** [comment]
Thanks for your interest. The code will be available this month.
